# Generated by Django 3.1.3 on 2020-12-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='index',
        ),
        migrations.AddField(
            model_name='dataset',
            name='data',
            field=models.FileField(default='', upload_to='datasets/'),
            preserve_default=False,
        ),
    ]
