# Generated by Django 3.1.3 on 2020-12-09 02:49

from django.db import migrations, models
import webui.models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0002_auto_20201209_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='data',
            field=models.FileField(upload_to=webui.models.dataset_id_path),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
