# Generated by Django 3.1.3 on 2020-12-09 04:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0005_auto_20201209_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fe9d8001-bb65-4872-8737-359ab74da4fe'), editable=False, primary_key=True, serialize=False),
        ),
    ]
