# Generated by Django 3.1.3 on 2020-12-09 04:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0007_auto_20201209_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f3f5770f-b8ac-477b-a2fe-f4286785a949'), editable=False, primary_key=True, serialize=False),
        ),
    ]
