# Generated by Django 3.1.3 on 2020-12-09 04:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0008_auto_20201209_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c62e565e-7893-45e4-bc4a-4c5bd3112f99'), editable=False, primary_key=True, serialize=False),
        ),
    ]
