# Generated by Django 3.1.3 on 2020-12-10 05:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0009_auto_20201209_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='id',
            field=models.UUIDField(default=uuid.UUID('91fb37bf-fc36-491e-a92b-c439f7d06766'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.IntegerField()),
                ('body', models.TextField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webui.dataset')),
            ],
        ),
    ]
