# Generated by Django 3.1.3 on 2020-12-10 06:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0010_auto_20201210_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='id',
            field=models.UUIDField(default=uuid.UUID('54002219-ccb1-4fc8-9514-d285f2a83412'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
