prefix = "."
stop-words = "../../stopwords.txt"

dataset = "dataset"
corpus = "../../../line.toml"
index = "idx"

query-judgements = "./dataset/qrels.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[query-runner]
query-path = "./dataset/queries.txt"
query-id-start = 1
